package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/abigotado/redmine-cli/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const generatedNotice = "<!-- Code generated by tools/gencommands. DO NOT EDIT. -->"

type flagInfo struct {
	Name, Shorthand, Type, Default, Usage string
}

type commandInfo struct {
	Path, Short, Args string
	Flags             []flagInfo
}

type commandTree struct {
	Globals  []flagInfo
	Commands []commandInfo
}

func collect(root *cobra.Command) commandTree {
	var tree commandTree
	root.PersistentFlags().VisitAll(func(flag *pflag.Flag) {
		if !flag.Hidden {
			tree.Globals = append(tree.Globals, describeFlag(flag))
		}
	})
	var walk func(*cobra.Command)
	walk = func(command *cobra.Command) {
		for _, child := range command.Commands() {
			if child.Hidden || child.IsAdditionalHelpTopicCommand() || child.Name() == "help" || child.Name() == "completion" {
				continue
			}
			if child.HasSubCommands() {
				walk(child)
				continue
			}
			info := commandInfo{Path: child.CommandPath(), Short: child.Short}
			if _, args, found := strings.Cut(child.Use, " "); found {
				info.Args = args
			}
			inherited := child.InheritedFlags()
			child.LocalFlags().VisitAll(func(flag *pflag.Flag) {
				if !flag.Hidden && inherited.Lookup(flag.Name) == nil {
					info.Flags = append(info.Flags, describeFlag(flag))
				}
			})
			sort.Slice(info.Flags, func(i, j int) bool { return info.Flags[i].Name < info.Flags[j].Name })
			tree.Commands = append(tree.Commands, info)
		}
	}
	walk(root)
	sort.Slice(tree.Globals, func(i, j int) bool { return tree.Globals[i].Name < tree.Globals[j].Name })
	sort.Slice(tree.Commands, func(i, j int) bool { return tree.Commands[i].Path < tree.Commands[j].Path })
	return tree
}

func describeFlag(flag *pflag.Flag) flagInfo {
	defaultValue := flag.DefValue
	if defaultValue == "false" || defaultValue == "[]" {
		defaultValue = ""
	}
	return flagInfo{Name: flag.Name, Shorthand: flag.Shorthand, Type: flag.Value.Type(), Default: defaultValue, Usage: flag.Usage}
}

func renderMarkdown(tree commandTree) string {
	var builder strings.Builder
	builder.WriteString(generatedNotice + "\n\n# Command reference\n\n")
	builder.WriteString("JSON mode writes one stable envelope to stdout and is the default when stdout is not a TTY. Text, raw, and help output are explicitly selected exceptions. Network commands require an explicit `--profile`; there is no active or default profile. See `contract.md` for exit codes and envelopes.\n\n")
	builder.WriteString("## Global flags\n\n| Flag | Type | Description |\n| --- | --- | --- |\n")
	for _, flag := range tree.Globals {
		builder.WriteString(fmt.Sprintf("| %s | %s | %s |\n", flagLabel(flag), flag.Type, flag.Usage))
	}
	builder.WriteString("\n## Commands\n\n")
	for _, command := range tree.Commands {
		builder.WriteString("### `" + command.Path + "`\n\n")
		if command.Short != "" {
			builder.WriteString(command.Short + "\n\n")
		}
		if command.Args != "" {
			builder.WriteString("Usage: `" + command.Path + " " + command.Args + "`\n\n")
		}
		if len(command.Flags) == 0 {
			builder.WriteString("No flags of its own.\n\n")
			continue
		}
		builder.WriteString("| Flag | Type | Default | Description |\n| --- | --- | --- | --- |\n")
		for _, flag := range command.Flags {
			builder.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", flagLabel(flag), flag.Type, code(flag.Default), flag.Usage))
		}
		builder.WriteString("\n")
	}
	return strings.TrimRight(builder.String(), "\n") + "\n"
}

func flagLabel(flag flagInfo) string {
	if flag.Shorthand != "" {
		return fmt.Sprintf("`-%s, --%s`", flag.Shorthand, flag.Name)
	}
	return "`--" + flag.Name + "`"
}

func code(value string) string {
	if value == "" {
		return ""
	}
	return "`" + value + "`"
}

func rootCommand() *cobra.Command {
	return cli.NewApp().NewRootCommand()
}
