// Command gencontract renders the stable machine contract from internal/errx.
package main

import (
	"fmt"
	"strings"

	"github.com/abigotado/redmine-cli/internal/errx"
)

const generatedNotice = "<!-- Code generated by tools/gencontract. DO NOT EDIT. -->"

func renderMarkdown(contract errx.Contract) string {
	var output strings.Builder
	profileRequired := errx.ProfileRequired()
	output.WriteString(generatedNotice)
	output.WriteString("\n\n# Machine contract\n\n")
	output.WriteString("Regenerate with `go generate ./...`.\n\n")
	output.WriteString("## Envelope\n\n")
	_, _ = fmt.Fprintf(&output, "Current version: `%d`.\n\n", contract.EnvelopeVersion)
	output.WriteString("```json\n")
	_, _ = fmt.Fprintf(&output, `{"ok":true,"v":%d,"data":[{"id":123,"subject":"Example"}],"meta":{"count":1,"truncated":true,"total_count":2,"offset":0,"limit":1,"next_cursor":"opaque","profile":"work","base_url":"https://redmine.example"}}`, contract.EnvelopeVersion)
	output.WriteByte('\n')
	_, _ = fmt.Fprintf(&output, `{"ok":false,"v":%d,"error":{"code":%q,"message":%q},"hint":%q}`, contract.EnvelopeVersion, profileRequired.Reason, profileRequired.Message, profileRequired.Hint)
	output.WriteString("\n```\n\n")
	output.WriteString("The top-level keys `ok`, `v`, `data`, `meta`, `error`, and `hint` are the\n")
	_, _ = fmt.Fprintf(&output, "v%d vocabulary. A field rename, removal, or type change requires an envelope\n", contract.EnvelopeVersion)
	output.WriteString("version bump. Optional `meta` fields are `count`, `truncated`, `total_count`,\n")
	output.WriteString("`offset`, `limit`, `next_cursor`, `profile`, and `base_url`; metadata never contains credentials.\n\n")
	output.WriteString("stdout receives exactly one compact JSON envelope in JSON mode. Diagnostics,\n")
	output.WriteString("prompts, warnings, and logs go to stderr. `error.code` is a stable\n")
	output.WriteString("`SCREAMING_SNAKE_CASE` value; add error detail there before considering a new\n")
	output.WriteString("process status.\n\n")
	output.WriteString("## Exit codes\n\n")
	output.WriteString("Each status maps to a distinct caller recovery action.\n\n")
	output.WriteString("| Code | Name | Meaning | Caller's next move |\n")
	output.WriteString("| ---: | --- | --- | --- |\n")
	for _, info := range contract.Codes {
		_, _ = fmt.Fprintf(&output, "| %d | `%s` | %s | %s |\n", info.Code, info.Name, info.Meaning, info.NextMove)
	}
	output.WriteString("\n## Recovery rules\n\n")
	output.WriteString("- Treat `403` as permission/scope denial (exit 8), not authentication.\n")
	output.WriteString("- Treat `409` as stale state/conflict (exit 9); re-read before another write.\n")
	output.WriteString("- Follow `next_cursor`; a full page does not prove the result is complete.\n")
	output.WriteString("- A compiled Go runtime can exit 2 after an unrecovered panic. The process entry\n")
	output.WriteString("  must recover ordinary panics and report exit 1 so they are not mistaken for\n")
	output.WriteString("  correct usage failures.\n")
	output.WriteString("- `redmine-cli contract` exposes the same table as JSON at runtime.\n")
	return output.String()
}
